--- #YAML:1.0
name:               Net-SMS-MunduSMS
version:            0.021
abstract:           Perl interface for sending SMS using the mundusms.com service.
author:
    - S Pradeep <spradeep@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    WWW::Mechanize:  1.54
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
